version: '3'

services:
  mongodb:
    image: "mongo:6.0.5"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=ce
      - MONGO_INITDB_ROOT_USERNAME=ce
      - MONGO_INITDB_ROOT_PASSWORD=ce
    volumes:
      - ./db/db-mongo/:/data/db
    ports:
      - 27017:27017
  mariadb:
    image: "mariadb:10.11"
    restart: always
    environment:
      MARIADB_DATABASE: ce
      MARIADB_USER: ce
      MARIADB_PASSWORD: ce
#      MARIADB_ROOT_USER: ce
      MARIADB_ROOT_PASSWORD: ce
    volumes:
      - ./db/db-maria/:/docker-entreypoint-initdb.d
    ports:
      - 3306:3306