
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.core 

# Auth0
auth0:
  audience: aimmoth-api-rs256
  domain: aimmoth.eu.auth0.com

spring:
  application:
    name: CE Spring Boot 3
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ce
      password: ce
      database: ce
      authentication-database: admin
#      uri: mongodb://localhost:27017/ce
      auto-index-creation: true
  datasource:
    url: jdbc:mariadb://localhost:3306/ce
    username: ce
    password: ce
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # drops all tables in database each start
  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: https://${auth0.domain}/


server:
  address: localhost
  port: 8084
  http2:
    enabled: true
  max-http-request-header-size: 8KB    

logging:
  level:
    ce: DEBUG

ce:
  multiplier: 113
---

