
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.core 

# Auth0
auth0:
  audience: auth0-api-identifier
  domain: auth0-tenant.eu.auth0.com

spring:
  application:
    name: CE Spring Boot 3
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ce
      password: ce
      database: ce
      authentication-database: admin
      auto-index-creation: true
  r2dbc:
      url: r2dbc:mariadb://localhost:3306/ce
      username: ce
      password: ce
  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: https://${auth0.domain}/


server:
  address: localhost
  port: 8084
  http2:
    enabled: true
  max-http-request-header-size: 8KB    

logging:
  level:
    org: INFO
    ce: DEBUG

ce:
  multiplier: 113
  security:
    cors: http://localhost:8084/
---

