
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.core 

spring:
  application:
    name: CE Spring Boot 3

server:
  address: 0.0.0.0
  port: 8080
#  http2:
#    enabled: true
#  max-http-request-header-size: 8KB

logging:
  level:
    org: INFO
    ce: DEBUG

ce:
  multiplier: 113
  security:
    webSocket: localhost:8080
---